name: Run Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */24 * * *" # run every 24 hours

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          echo "source $HOME/.nvm/nvm.sh" >> $GITHUB_ENV

      - name: Set Node version using NVM
        shell: bash
        run: |
          source $HOME/.nvm/nvm.sh
          nvm install
          nvm use

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: npm start
