name: Run Discord Bot

on:
  schedule:
    - cron: "0 */24 * * *" # run every 24 hours

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # custom token not the same as GITHUB_TOKEN
          token: ${{ secrets.GH_TOKEN }} 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          npm start
          if [ $? -eq 0 ]; then
            if [ -n "$(git status --porcelain data/fetchedissues.json)" ]; then
              echo "Changes detected. Committing updates..."
              git config --local user.name "github-actions"
              git config --local user.email "action@github.com"
              git add data/fetchedissues.json
              git commit -m "Update fetched issues from cron job"
              git push origin HEAD:main
            else
              echo "No changes to commit."
            fi
          else
            echo "Bot execution failed. No changes will be committed."
            exit 1
          fi
