name: Run Discord Bot

on:
  schedule:
    - cron: "0 */24 * * *" # run every 24 hours
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ACTIONS_PUSH_TOKEN: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          echo "=== Starting the Discord Bot ==="
          npm start

          # bot exits on code 0 when npm start completes
          BOT_EXIT_CODE=$?
          if [ $BOT_EXIT_CODE -eq 0 ]; then
            echo "Bot executed successfully."
            echo "=== Checking for changes in fetched_issues.json ==="

            # verify fetched_issues.json has been modified
            if [ -n "$(git status --porcelain data/fetched_issues.json)" ]; then
              echo "Changes detected in fetched_issues.json. Committing updates..."
              git config --local user.name "github-actions"
              git config --local user.email "action@github.com"
              git add data/fetched_issues.json
              git commit -m "Update fetched issues from cron job"

              echo "=== Pushing changes to main branch ==="
              git push origin main
            else
              echo "No changes to commit."
            fi
          else
            echo "Bot execution failed with exit code $BOT_EXIT_CODE. No changes will be committed."
            exit $BOT_EXIT_CODE
          fi
